### ISSUE TITLE
Hell Background

### ISSUE THREAD

**Issue by BenJLubrano** [BenJLubrano/Team-Vania-Platformer#111]

**Comment by KhangDangPham** [comment]
Here is the Lava Background 
![Lava Background](https://user-images.githubusercontent.com/71156942/100389705-baa70b00-2ff3-11eb-85ec-a094c4d13dbf.png)

**Comment by KhangDangPham** [comment]
Here is the updated lava background
![Lava Background](https://user-images.githubusercontent.com/71156942/100682669-3975ae00-333c-11eb-9803-3eace6e12a22.png)
