### ISSUE TITLE
Cave Assets

### ISSUE THREAD

**Issue by KhangDangPham** [BenJLubrano/Team-Vania-Platformer#51]
I just created the Cave rocks and spike
![Cave Spike](https://user-images.githubusercontent.com/71156942/98882684-6415ca80-2452-11eb-8718-0774563c4433.png)
![Rock 1](https://user-images.githubusercontent.com/71156942/98882691-64ae6100-2452-11eb-99e6-633a808dcec9.png)
![Rock 2](https://user-images.githubusercontent.com/71156942/98882693-64ae6100-2452-11eb-8b2b-6e4a817c272e.png)
![Rock 3](https://user-images.githubusercontent.com/71156942/98882695-64ae6100-2452-11eb-810a-1ff1f1d2a2a8.png)

**Comment by BenJLubrano** [comment]
Changed the title again, you had it right the first time. "Khang-Issue51" should be the name of the BRANCH. This is the issue, so it should be named whatever describes what it contains

**Comment by BenJLubrano** [comment]
Merged/Handled in another issue
