### ISSUE TITLE
Cave Background

### ISSUE THREAD

**Issue by KhangDangPham** [BenJLubrano/Team-Vania-Platformer#58]
Here is the cave background
![Cave Background](https://user-images.githubusercontent.com/71156942/99756086-f00e9e80-2ab1-11eb-8fe4-2e4e7aeae86b.png)

**Comment by KhangDangPham** [comment]
![Cave Background](https://user-images.githubusercontent.com/71156942/99916076-7fdc6480-2ccd-11eb-91b2-4e67c8f84a39.png)
Here is the updated Cave Background

**Comment by BenJLubrano** [comment]
Handled in another issue
